# Generated by Django 3.1.3 on 2021-01-24 00:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
