# Generated by Django 3.1.3 on 2020-11-24 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='start',
            field=models.DateTimeField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
