# Generated by Django 3.1.3 on 2020-11-24 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20201124_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
