# Generated by Django 3.1.3 on 2021-04-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start',
            field=models.DateField(),
        ),
    ]
