# Generated by Django 3.1.3 on 2021-04-30 02:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', tinymce.models.HTMLField()),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', tinymce.models.HTMLField()),
                ('repoLink', models.URLField()),
            ],
        ),
    ]
